# Site settings
author: nathalie
title: you and I code
header-img: img/home-bg.png
email: nathalie.scruz@gmail.com
copyright_name: nathalie
description: > # this means to ignore newlines until "baseurl:"
  once upon a code
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  nathaliesantana

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
